### ISSUE TITLE
Rails 4.0 - cannot load such file -- active_support/memoizable (LoadError)

### ISSUE THREAD

**Issue by theinventor** [waynerobinson/xeroizer#133]
Hey, we are upgrading our app and get this error when going from 3.2.17 to 4.0.0

Commenting this line does allow the app to boot up;

```
/Users/troy/.rvm/gems/ruby-1.9.3-p0@railsfour/gems/activesupport-4.0.0/lib/active_support/dependencies.rb:228:in `require': cannot load such file -- active_support/memoizable (LoadError)
    from /Users/troy/.rvm/gems/ruby-1.9.3-p0@railsfour/gems/activesupport-4.0.0/lib/active_support/dependencies.rb:228:in `block in require'
    from /Users/troy/.rvm/gems/ruby-1.9.3-p0@railsfour/gems/activesupport-4.0.0/lib/active_support/dependencies.rb:213:in `load_dependency'
    from /Users/troy/.rvm/gems/ruby-1.9.3-p0@railsfour/gems/activesupport-4.0.0/lib/active_support/dependencies.rb:228:in `require'
    from /Users/troy/.rvm/gems/ruby-1.9.3-p0@railsfour/gems/xeroizer-2.15.0/lib/xeroizer.rb:5:in `<top (required)>'
```

Any ideas? Love the gem :)

**Comment by CloCkWeRX** [comment]
Payroll branch still requires this

**Comment by CloCkWeRX** [comment]
36821b57e1fca8ce6b4bf9a79e8f45d49b42565b
