### ISSUE TITLE
undefined method `contact_persons='

### ISSUE THREAD

**Issue by forrest** [waynerobinson/xeroizer#143]
When using `batch_save`, I periodically receive this error. I never write to `contact_persons` or `contact_people` so I'm not sure where this is coming from.

```
Error during sync: undefined method `contact_persons=' for #<Xeroizer::Record::Contact:0x00000107aebe80>
/Users/forrest/.rvm/gems/ruby-2.1.1/bundler/gems/xeroizer-d82d83011096/lib/xeroizer/record/base.rb:68:in `block in attributes='
/Users/forrest/.rvm/gems/ruby-2.1.1/bundler/gems/xeroizer-d82d83011096/lib/xeroizer/record/base.rb:67:in `each'
/Users/forrest/.rvm/gems/ruby-2.1.1/bundler/gems/xeroizer-d82d83011096/lib/xeroizer/record/base.rb:67:in `attributes='
/Users/forrest/.rvm/gems/ruby-2.1.1/bundler/gems/xeroizer-d82d83011096/lib/xeroizer/record/base_model.rb:160:in `block (3 levels) in batch_save'
/Users/forrest/.rvm/gems/ruby-2.1.1/bundler/gems/xeroizer-d82d83011096/lib/xeroizer/record/base_model.rb:158:in `each'
/Users/forrest/.rvm/gems/ruby-2.1.1/bundler/gems/xeroizer-d82d83011096/lib/xeroizer/record/base_model.rb:158:in `each_with_index'
/Users/forrest/.rvm/gems/ruby-2.1.1/bundler/gems/xeroizer-d82d83011096/lib/xeroizer/record/base_model.rb:158:in `block (2 levels) in batch_save'
/Users/forrest/.rvm/gems/ruby-2.1.1/bundler/gems/xeroizer-d82d83011096/lib/xeroizer/record/base_model.rb:155:in `each_slice'
/Users/forrest/.rvm/gems/ruby-2.1.1/bundler/gems/xeroizer-d82d83011096/lib/xeroizer/record/base_model.rb:155:in `block in batch_save'
/Users/forrest/.rvm/gems/ruby-2.1.1/bundler/gems/xeroizer-d82d83011096/lib/xeroizer/record/base_model.rb:154:in `each_pair'
/Users/forrest/.rvm/gems/ruby-2.1.1/bundler/gems/xeroizer-d82d83011096/lib/xeroizer/record/base_model.rb:154:in `batch_save'
...
```

**Comment by CloCkWeRX** [comment]
I'm confused by https://github.com/waynerobinson/xeroizer/blob/master/lib/xeroizer/models/contact.rb#L46 - the API itself refers to it as ContactPersons (
http://developer.xero.com/documentation/api/contacts/#contact-persons). Nothing else in the codebase refers to contact_people, unless there's some weird inflection stuff happening.

Should it be

```
has_many  :contact_persons, :model_name => "ContactPerson"
```
not
```
has_many  :contact_persons, :internal_name => :contact_people
```
