### ISSUE TITLE
Unhandled  error when payroll API not authorised

### ISSUE THREAD

**Issue by CloCkWeRX** [waynerobinson/xeroizer#204]
This might be better for @ghiculescu rather than here in master; but there's no issues turned on there, so.

```
GIT
  remote: https://github.com/ghiculescu/xeroizer.git
  revision: c0c509cb09497eb14640848ab72e540aa989d8a8
  branch: payroll
  specs:
    xeroizer (2.15.5)
```
1. Private key application
2. Try to access something where the payroll api is not authorised

Expected: something like

```
/srv/xero-data/releases/0.0.19/.bundle/ruby/2.1.0/bundler/gems/xeroizer-c0c509cb0949/lib/xeroizer/http.rb:148:in `handle_oauth_error!': {"<ApiException xmlns:i"=>["\"http://www.w3.org/2001/XMLSchema-instance\"><ErrorNumber>0</ErrorNumber><Type>Error</Type><Message>Payroll API access not authorised</Message></ApiException>"]} (Xeroizer::OAuth::UnknownError)
```

actual:

```
I, [2015-03-18T16:30:17.495682 #31302]  INFO -- : Setup
/srv/xero-data/releases/0.0.19/.bundle/ruby/2.1.0/bundler/gems/xeroizer-c0c509cb0949/lib/xeroizer/http.rb:148:in `handle_oauth_error!': undefined method `+' for nil:NilClass (NoMethodError)
    from /srv/xero-data/releases/0.0.19/.bundle/ruby/2.1.0/bundler/gems/xeroizer-c0c509cb0949/lib/xeroizer/http.rb:116:in `http_request'
    from /srv/xero-data/releases/0.0.19/.bundle/ruby/2.1.0/bundler/gems/xeroizer-c0c509cb0949/lib/xeroizer/http.rb:29:in `http_get'
    from /srv/xero-data/releases/0.0.19/.bundle/ruby/2.1.0/bundler/gems/xeroizer-c0c509cb0949/lib/xeroizer/application_http_proxy.rb:16:in `http_get'
    from /srv/xero-data/releases/0.0.19/.bundle/ruby/2.1.0/bundler/gems/xeroizer-c0c509cb0949/lib/xeroizer/record/base_model.rb:129:in `all'
    from /srv/xero-data/releases/0.0.19/lib/leave_fetcher.rb:38:in `employees'
    from fetch.rb:23:in `block in <main>'
    from fetch.rb:18:in `each'
    from fetch.rb:18:in `<main>'

```

Due to

```
        # see http://oauth.pbworks.com/ProblemReporting
        # In addition to token_expired and token_rejected, Xero also returns
        # 'rate limit exceeded' when more than 60 requests have been made in
        # a second.
        case (error_details["oauth_problem"].first)
          when "token_expired"        then raise OAuth::TokenExpired.new(description)
          when "token_rejected"       then raise OAuth::TokenInvalid.new(description)
          when "rate limit exceeded"  then raise OAuth::RateLimitExceeded.new(description)
          else raise OAuth::UnknownError.new( .... ) # this fails when oauth_problem is nil
        end

```

**Comment by ghiculescu** [comment]
Ooops, I've opened up issues on my fork.

I think that PR is a good fix, I've added a question though.
