### ISSUE TITLE
Rails 5: Calling to_s on a BigDecimal results in an infinite loop

### ISSUE THREAD

**Issue by benpritchard** [waynerobinson/xeroizer#280]
https://github.com/waynerobinson/xeroizer/blob/960e78c89771c7486bae68c4e187b8530ee4782a/lib/big_decimal_to_s.rb#L3

``` ruby
class BigDecimal

  def to_s_with_default_format(format = 'F')
    to_s_without_default_format(format)
  end
  alias_method :to_s_without_default_format, :to_s
  alias_method :to_s, :to_s_with_default_format

end
```

With rails 5.0.0.beta2, calling `to_s` on a BigDecimal and xeroizer installed results in an infinite loop.

Sample backtrace:

``` sh
     # /Users/ben/.rvm/gems/ruby-2.2.4/gems/activesupport-5.0.0.beta2/lib/active_support/core_ext/big_decimal/conversions.rb:9:in `to_s'
     # /Users/ben/.rvm/gems/ruby-2.2.4/gems/xeroizer-2.16.1/lib/big_decimal_to_s.rb:4:in `to_s_with_default_format'
     # /Users/ben/.rvm/gems/ruby-2.2.4/gems/activesupport-5.0.0.beta2/lib/active_support/core_ext/big_decimal/conversions.rb:9:in `to_s'
     # /Users/ben/.rvm/gems/ruby-2.2.4/gems/xeroizer-2.16.1/lib/big_decimal_to_s.rb:4:in `to_s_with_default_format'
     # /Users/ben/.rvm/gems/ruby-2.2.4/gems/activesupport-5.0.0.beta2/lib/active_support/core_ext/big_decimal/conversions.rb:9:in `to_s'
     # /Users/ben/.rvm/gems/ruby-2.2.4/gems/xeroizer-2.16.1/lib/big_decimal_to_s.rb:4:in `to_s_with_default_format'
     # /Users/ben/.rvm/gems/ruby-2.2.4/gems/activesupport-5.0.0.beta2/lib/active_support/core_ext/big_decimal/conversions.rb:9:in `to_s'
     # /Users/ben/.rvm/gems/ruby-2.2.4/gems/xeroizer-2.16.1/lib/big_decimal_to_s.rb:4:in `to_s_with_default_format'
     # /Users/ben/.rvm/gems/ruby-2.2.4/gems/activesupport-5.0.0.beta2/lib/active_support/core_ext/big_decimal/conversions.rb:9:in `to_s'
     # /Users/ben/.rvm/gems/ruby-2.2.4/gems/xeroizer-2.16.1/lib/big_decimal_to_s.rb:4:in `to_s_with_default_format'
     # /Users/ben/.rvm/gems/ruby-2.2.4/gems/activesupport-5.0.0.beta2/lib/active_support/core_ext/big_decimal/conversions.rb:9:in `to_s'

     # /Users/ben/.rvm/gems/ruby-2.2.4/gems/xeroizer-2.16.1/lib/big_decimal_to_s.rb:4:in `to_s_with_default_format'
     # /Users/ben/.rvm/gems/ruby-2.2.4/gems/activesupport-5.0.0.beta2/lib/active_support/core_ext/big_decimal/conversions.rb:9:in `to_s'
     # /Users/ben/.rvm/gems/ruby-2.2.4/gems/activesupport-5.0.0.beta2/lib/active_support/core_ext/numeric/conversions.rb:126:in `to_s'
```

This seems to be the commit that changed things: https://github.com/rails/rails/commit/f61dd4f9d4c48b1d447b499d0541d2f6421aedd7

**Comment by Schwad** [comment]
Got this same issue, thanks for the fix.

**Comment by bendangelo** [comment]
Thanks for the fix.

**Comment by Rio517** [comment]
Now if we could just get the version bummed up so folks aren't running around trying to figure out why their upgraded app is so freaking slow. Thanks!

**Comment by SylarRuby** [comment]
Oh. Where're the fix? https://github.com/waynerobinson/xeroizer/issues/317
