### ISSUE TITLE
NoMethodError: undefined method `[]' for nil:NilClass when using add_{association} method

### ISSUE THREAD

**Issue by basco-johnkevin** [waynerobinson/xeroizer#346]
```
contact = xero.Contact.find("a91dea31-f8e2-4532-80f1-e3c30c89422e")

invoice = xero.Invoice.build(:type => "ACCPAY", :contact => contact, :date => Date.today, :due_date => (Date.today + 1.year).to_s, :line_amount_types => "Exclusive", :invoice_number => "41e83b29a03ke8fe")

item = xero.Item.first(:where => {:code => "Yokohama321242156016"})

invoice.add_line_item(:description => "Yokohama", :quantity => 1, :unit_amount => 100, :code => "Yokohama321242156016")
```

The error happens when I execute this line of code: `invoice.add_line_item(:description => "Yokohama", :quantity => 1, :unit_amount => 100, :code => "Yokohama321242156016")`

This is the error:

```
NoMethodError: undefined method `[]' for nil:NilClass
  from /var/www/tire-website/releases/167/vendor/bundle/ruby/2.2.0/bundler/gems/xeroizer-76932e36b22c/lib/xeroizer/record/base.rb:33:in `block in build'
  from /var/www/tire-website/releases/167/vendor/bundle/ruby/2.2.0/bundler/gems/xeroizer-76932e36b22c/lib/xeroizer/record/base.rb:32:in `each'
  from /var/www/tire-website/releases/167/vendor/bundle/ruby/2.2.0/bundler/gems/xeroizer-76932e36b22c/lib/xeroizer/record/base.rb:32:in `build'
  from /var/www/tire-website/releases/167/vendor/bundle/ruby/2.2.0/bundler/gems/xeroizer-76932e36b22c/lib/xeroizer/record/record_association_helper.rb:72:in `block (2 levels) in has_many'
  from /var/www/tire-website/releases/167/vendor/bundle/ruby/2.2.0/bundler/gems/xeroizer-76932e36b22c/lib/xeroizer/record/record_association_helper.rb:71:in `each'
  from /var/www/tire-website/releases/167/vendor/bundle/ruby/2.2.0/bundler/gems/xeroizer-76932e36b22c/lib/xeroizer/record/record_association_helper.rb:71:in `block in has_many'
  from (irb):6
  from /var/www/tire-website/releases/167/vendor/bundle/ruby/2.2.0/gems/railties-4.2.6/lib/rails/commands/console.rb:110:in `start'
  from /var/www/tire-website/releases/167/vendor/bundle/ruby/2.2.0/gems/railties-4.2.6/lib/rails/commands/console.rb:9:in `start'
  from /var/www/tire-website/releases/167/vendor/bundle/ruby/2.2.0/gems/railties-4.2.6/lib/rails/commands/commands_tasks.rb:68:in `console'
  from /var/www/tire-website/releases/167/vendor/bundle/ruby/2.2.0/gems/railties-4.2.6/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
  from /var/www/tire-website/releases/167/vendor/bundle/ruby/2.2.0/gems/railties-4.2.6/lib/rails/commands.rb:17:in `<top (required)>'
  from bin/rails:9:in `require'
  from bin/rails:9:in `<main>'
  ```

Am I doing something wrong? or this is a bug?

Currently using:

```
GIT
  remote: git://github.com/waynerobinson/xeroizer.git
  revision: 76932e36b22c0cbfc2a1b3d3fbbb0860b1dc2546
  specs:
    xeroizer (2.16.5)
      activesupport
      builder (>= 2.1.2)
      i18n
      nokogiri
      oauth (>= 0.4.5)
      tzinfo
```

Rails 4.2.6
ruby 2.2.5p319 (2016-04-26 revision 54774) [x86_64-linux]

**Comment by waynerobinson** [comment]
Is the contact nil?

**Comment by basco-johnkevin** [comment]
@waynerobinson Nope. 

```
#<Xeroizer::Record::Contact :contact_id: "a91dea31-f8e2-4532-80f1-e3c30c89422e", :account_number: "distributor-1-786760ace0929425", :contact_status: "ACTIVE">
```

I removed other fields from the object above for brevity.

**Comment by basco-johnkevin** [comment]
@waynerobinson Any other idea what's causing the issue? I tried using old releases of xeroizer but I can't make them work. Getting a cert related error.

**Comment by basco-johnkevin** [comment]
@waynerobinson Finally found what's causing the error. I should use `:item_code` instead of `:code` for adding line items.

`invoice.add_line_item(:description => "Yokohama", :quantity => 1, :unit_amount => 100, :item_code => "Yokohama321242156016")`

instead of 

`invoice.add_line_item(:description => "Yokohama", :quantity => 1, :unit_amount => 100, :code => "Yokohama321242156016")`

Will it be possible to improve the errors being provided by xeroizer?
