### ISSUE TITLE
Point release for Partner API URL changes?

### ISSUE THREAD

**Issue by toxaq** [waynerobinson/xeroizer#364]
HI team, I see the new partner API endpoints have been changed on master. Is it possible to get a point release for this change? 

Thanks again for this gem.

**Comment by waynerobinson** [comment]
@CloCkWeRX please let me know whenever you'd like me to push a release and if you've changed anything about the gem build process.

**Comment by CloCkWeRX** [comment]
Yeah, lets do that for 2.17.0. Nothing in the build process should be different afaik.

**Comment by toxaq** [comment]
I can confirm that the changes on master worked for my partner app if that helps.

**Comment by nagash** [comment]
I am also waiting for this release, our certificate expires in June so will have to switch over by then.

**Comment by orangethunder** [comment]
+1 for this. Can confirm that we're using master successfully in production (due to pending certificate expiry)

**Comment by lesliev** [comment]
+1 can you please release this? I tried to just change `:xero_url` and `:site` when constructing the PartnerApplication (as Xero tells us to do), but that did not work. 

I assume the relevant changes are in: https://github.com/waynerobinson/xeroizer/commit/052723aa279d32e150fcf82cf1aad936f08936f4, which also removes `:private_key_file`, `:ssl_client_cert` and `:ssl_client_key` from the options hash. 

I will try master branch later today.

This was the exception I got when trying to `Xeroizer::PartnerApplication.new(x).Account.all`:

```2017-10-02T19:36:01.444Z 11684 TID-ouzgxk3hc SyncXeroJob JID-8e8b1d5066d31f1584af2aea INFO: Adding dead ActiveJob::QueueAdapters::SidekiqAdapter::JobWrapper job 8e8b1d5
2017-10-02T19:36:01.444Z 11684 TID-ouzgxk3hc SyncXeroJob JID-8e8b1d5066d31f1584af2aea INFO: fail: 0.45 sec
2017-10-02T19:36:01.444Z 11684 TID-ouzgxk3hc WARN: {"class":"ActiveJob::QueueAdapters::SidekiqAdapter::JobWrapper","wrapped":"SyncXeroJob","queue":"xero","args":[{"job_
2017-10-02T19:36:01.444Z 11684 TID-ouzgxk3hc WARN: OpenSSL::SSL::SSLError: SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify fail
2017-10-02T19:36:01.444Z 11684 TID-ouzgxk3hc WARN: /usr/lib/ruby/2.3.0/net/http.rb:933:in `connect_nonblock'
/usr/lib/ruby/2.3.0/net/http.rb:933:in `connect'
/usr/lib/ruby/2.3.0/net/http.rb:863:in `do_start'
/usr/lib/ruby/2.3.0/net/http.rb:852:in `start'
/usr/lib/ruby/2.3.0/net/http.rb:1398:in `request'
/home/deploy/apps/refserf_production/shared/bundle/ruby/2.3.0/gems/newrelic_rpm-3.17.1.326/lib/new_relic/agent/instrumentation/net.rb:27:in `block (2 levels) in request
/home/deploy/apps/refserf_production/shared/bundle/ruby/2.3.0/gems/newrelic_rpm-3.17.1.326/lib/new_relic/agent.rb:443:in `disable_all_tracing'
/home/deploy/apps/refserf_production/shared/bundle/ruby/2.3.0/gems/newrelic_rpm-3.17.1.326/lib/new_relic/agent/instrumentation/net.rb:26:in `block in request_with_newre
/home/deploy/apps/refserf_production/shared/bundle/ruby/2.3.0/gems/newrelic_rpm-3.17.1.326/lib/new_relic/agent/cross_app_tracing.rb:48:in `tl_trace_http_request'
/home/deploy/apps/refserf_production/shared/bundle/ruby/2.3.0/gems/newrelic_rpm-3.17.1.326/lib/new_relic/agent/instrumentation/net.rb:23:in `request_with_newrelic_trace
/home/deploy/apps/refserf_production/shared/bundle/ruby/2.3.0/gems/oauth-0.5.1/lib/oauth/consumer.rb:161:in `request'
/home/deploy/apps/refserf_production/shared/bundle/ruby/2.3.0/gems/oauth-0.5.1/lib/oauth/tokens/consumer_token.rb:25:in `request'
/home/deploy/apps/refserf_production/shared/bundle/ruby/2.3.0/gems/oauth-0.5.1/lib/oauth/tokens/access_token.rb:12:in `request'
/home/deploy/apps/refserf_production/shared/bundle/ruby/2.3.0/gems/oauth-0.5.1/lib/oauth/tokens/access_token.rb:27:in `get'
/home/deploy/apps/refserf_production/shared/bundle/ruby/2.3.0/bundler/gems/xeroizer-f8e195f50661/lib/xeroizer/http.rb:105:in `block in http_request'
/home/deploy/apps/refserf_production/shared/bundle/ruby/2.3.0/bundler/gems/xeroizer-f8e195f50661/lib/xeroizer/http.rb:103:in `loop'
/home/deploy/apps/refserf_production/shared/bundle/ruby/2.3.0/bundler/gems/xeroizer-f8e195f50661/lib/xeroizer/http.rb:103:in `http_request'
/home/deploy/apps/refserf_production/shared/bundle/ruby/2.3.0/bundler/gems/xeroizer-f8e195f50661/lib/xeroizer/http.rb:31:in `http_get'
/home/deploy/apps/refserf_production/shared/bundle/ruby/2.3.0/bundler/gems/xeroizer-f8e195f50661/lib/xeroizer/application_http_proxy.rb:16:in `http_get'
/home/deploy/apps/refserf_production/shared/bundle/ruby/2.3.0/bundler/gems/xeroizer-f8e195f50661/lib/xeroizer/record/base_model.rb:120:in `all'
/home/deploy/apps/refserf_production/releases/20171002021826/app/jobs/sync_chart_accounts_job.rb:28:in `perform'
/home/deploy/apps/refserf_production/shared/bundle/ruby/2.3.0/gems/activejob-5.0.0.1/lib/active_job/exec```

**Comment by rjaus** [comment]
New version has been released and pushed to RubyGems: https://rubygems.org/gems/xeroizer/versions/2.17.0

This version includes the deprecation of entrust certs and the partner api url change: https://github.com/waynerobinson/xeroizer/releases/tag/v2.17.0
