### ISSUE TITLE
trying to run tests as a developer...

### ISSUE THREAD

**Issue by timdiggins** [waynerobinson/xeroizer#549]
I'm trying to run the tests as a developer (working on #538 )

I've set up a Demo company and custom connection and set `export XERO_CLIENT_ID=` to given id and created as secret and set it locally as `export XERO_CLIENT_SECRET=`. However it's not that obvious how or what to set `XERO_ACCESS_TOKEN` and `XERO_TENANT_ID` to. As a result some of the non-unit tests are failing. But that's noise. Everything else passes when I do `bundle exec rake test`

I'm trying to run one file but when I try `bundle exec rake test TEST=test/unit/record/base_test.rb` I get lots of these kind of tracebacks:

```
Error: test: saving invalid record should return false saving with #save. (RecordBaseTest): NoMethodError: undefined method `stubs' for #<Xeroizer::Record::Contact :name: "Test Contact Name ABC">
/Users/xxx/workspaces/xxx/xeroizer/test/unit/record/base_test.rb:121:in `block (3 levels) in <class:RecordBaseTest>'
/Users/xxx/.rvm/gems/ruby-2.7.3@xeroizer/gems/shoulda-context-1.2.2/lib/shoulda/context/context.rb:438:in `instance_exec'
/Users/xxx/.rvm/gems/ruby-2.7.3@xeroizer/gems/shoulda-context-1.2.2/lib/shoulda/context/context.rb:438:in `block in run_current_setup_blocks'
/Users/xxx/.rvm/gems/ruby-2.7.3@xeroizer/gems/shoulda-context-1.2.2/lib/shoulda/context/context.rb:436:in `each'
/Users/xxx/.rvm/gems/ruby-2.7.3@xeroizer/gems/shoulda-context-1.2.2/lib/shoulda/context/context.rb:436:in `run_current_setup_blocks'
/Users/xxx/workspaces/xxx/xeroizer/test/unit/record/base_test.rb:144:in `block in create_test_from_should_hash'
```

I don't often use minitest/shoulda but somether here is not set up correctly when running a single test.

Any ideas?

**Comment by timdiggins** [comment]
Thanks Riley. What do you think about adding vcr to the test setup  and making the setup and (re)generation of the vcr cassettes a manual occasional process for developers? 

However maybe given that xero are behind https://github.com/XeroAPI/xero-ruby maybe it's more sensible for me to focus efforts on switching to that gem rather than pouring effort into this one.
